---
- hosts: all
  tasks:
  - name: create a new user
    sudo: yes
    user: name=web
          state=present
          group=sudo
          groups="sudo"
          password="any"
  - name: update apt cache
    sudo: yes
    apt: update_cache=yes cache_valid_time=3600
  - name: install apt packages
    sudo: yes
    apt: name={{item}} state=present
    with_items:
       - git
  - synchronize: src=discourse-source dest=/var/discourse
    sudo: yes
  - command: wget -qO- https://get.docker.com/ | sh
    sudo: yes
  - service: name=docker state=restarted
    sudo: yes
  - command: /var/discourse/discourse-source/launcher bootstrap app
    sudo: yes
  - command: /var/discourse/discourse-source/launcher start app
    sudo: yes
