---
- hosts: all
  sudo: yes
  roles:
    - angstwad.docker_ubuntu
  post_tasks:
  - name: add discourse user
    user: name=discourse groups=sudo,admin
  - synchronize: src=discourse dest=/var/
    sudo: yes
  - shell: docker ps
    sudo: yes
    register: discourse_running
  - debug: msg="discourse_running {{discourse_running}}"
  - service: name=docker state=restarted
    sudo: yes
  - command: docker ps -qa
    register: docker_ps_qa
    sudo: yes
  - command: ./launcher bootstrap app
    args:
      chdir: /var/discourse
    when: discourse_running.stdout.find('local_discourse/app') == -1
    sudo: yes
  - command: docker ps -qa
    register: docker_ps_qa
    sudo: yes
  - debug: msg="{{docker_ps_qa}}"
  # - command: docker rm -f "{{docker_ps_qa.stdout}}"
  #   when: docker_ps_qa.stdout_lines != []
  #   sudo: yes
  - command: ./launcher stop app
    when: docker_ps_qa.stdout_lines != []
    args:
      chdir: /var/discourse
    sudo: yes
  - command: ./launcher start app
    args:
      chdir: /var/discourse
    sudo: yes
