---
#Variables for ansible-role-aws-tools
install_awscli: true
install_logs_agent: false
install_custom_metrics: true
install_codedeploy: false
install_cfn_bootstrap: false

# where to install discourse
discourse_location: /var/discourse