---
# where to install discourse
discourse_location: /var/discourse

# https://github.com/angstwad/docker.ubuntu
update_docker_package: no

ntp_timezone: Europe/Rome
ntp_enabled: true
ntp_manage_config: false
ntp_servers:
  - 0.pool.ntp.org iburst
  - 1.pool.ntp.org iburst
  - 2.pool.ntp.org iburst
  - 3.pool.ntp.org iburst

firewall_allowed_tcp_ports:
  - "22"
  - "80"
  - "443"

#Variables for ansible-role-aws-tools
install_awscli: true
install_logs_agent: false
install_custom_metrics: true
install_codedeploy: false
install_cfn_bootstrap: false