---
AWSTemplateFormatVersion: '2010-09-09'
Description: SSM Parameters for discourse deployment

Parameters:
  pDiscourseCommonCustomer:
    Type: String
    Default: "default"
    Description: Name of customer or company
  pDiscourseCommonDomainName:
    Type: String
    Default: "default"
    Description: Domain name == route53 hosted zone name
  pDiscourseCommonApplicationName:
    Type: String
    Default: "discourse"
    Description: Name of application. It should be discourse
  pDiscourseCommonEnvironmentVersion:
    Type: String
    Default: "v0"
    Description: Version number. It is always override by pipeline
  pDiscourseCommonSubnetIdA:
    Type: String
    Default: "default"
    Description: Subnet-A to use for application
  pDiscourseCommonSubnetIdB:
    Type: String
    Default: "default"
    Description: Subnet-B to use for application
  pDiscourseCommonVPCcidr:
    Type: String
    Default: "default"
    Description: VPC CIDR
  pDiscourseCommonVpcId:
    Type: String
    Default: "default"
    Description: VPC id to use for application
  pDiscourseRdsDBInstanceType:
    Type: String
    Default: "default"
    Description: RDS instance type for postgres
  pDiscourseRdsDBPassword:
    Type: String
    Default: "default"
    Description: Default password for postgres. Ignored if db is restored from snapshot
  pDiscourseRdsPostgresEngineVersion:
    Type: String
    Default: "11.1"
    Description: Postgres version of database
  pDiscourseRdsRDSSnapshotName:
    Type: String
    Default: "default"
    Description: Name of the snapshot from which recover db. Leave it empty if new database
  pDiscourseAppAMIid:
    Type: String
    Default: "default"
    Description: Golden AMI id. It is always override by pipeline
  pDiscourseAppCertificateARN:
    Type: String
    Default: "default"
    Description: ARN of load balancer certificate
  pDiscourseAppInstanceName:
    Type: String
    Default: "discourse"
    Description: Name of the EC2 instance
  pDiscourseAppInstanceType:
    Type: String
    Default: "default"
    Description: EC2 type
  pDiscourseAppKeyName:
    Type: String
    Default: "default"
    Description: Keyname for EC2
  pDiscourseAppSshCidrAllow:
    Type: String
    Default: "default"
    Description: CIDR of allowed IPs for ssh connection to instance
  pDiscoursePipelineBucketName:
    Type: String
    Default: "default"
    Description: Name of S3 bucket where pipeline store artifacts
  pDiscoursePipelineCodeBuildComputeType:
    Type: String
    Default: "default"
    Description: Codebuild size type
  pDiscoursePipelineCodeBuildEnvironment:
    Type: String
    Default: "default"
    Description: Codebuild container name
  pDiscoursePipelineGitHubRepoName:
    Type: String
    Default: "default"
    Description: Name of github repo from which get the code
  pDiscoursePipelineGitHubToken:
    Type: String
    Default: "default"
    Description: Token for reading github repository
  pDiscoursePipelineGitHubUsername:
    Type: String
    Default: "xpeppers"
    Description: Username or organization name of repository owner
  pDiscoursePipelineNotificationMail:
    Type: String
    Default: "xpeppers-discourse"
    Description: Mail to send pipeline notification

Resources:

#common
  DiscourseCommonCustomer:
    Type: AWS::SSM::Parameter
    Properties:
      Name: discourse-common-Customer
      Type: String
      Description: Name of customer or company
      Value: !Ref pDiscourseCommonCustomer

  DiscourseCommonDomainName:
    Type: AWS::SSM::Parameter
    Properties:
      Name: discourse-common-DomainName
      Type: String
      Description: Domain name == route53 hosted zone name
      Value: !Ref pDiscourseCommonDomainName

  DiscourseCommonApplicationName:
    Type: AWS::SSM::Parameter
    Properties:
      Name: discourse-common-ApplicationName
      Type: String
      Description: Name of application. It should be discourse
      Value: !Ref pDiscourseCommonApplicationName

  DiscourseCommonEnvironmentVersion:
    Type: AWS::SSM::Parameter
    Properties:
      Name: discourse-common-EnvironmentVersion
      Type: String
      Description: Version number. It is always override by pipeline
      Value: !Ref pDiscourseCommonEnvironmentVersion

# network
  DiscourseCommonSubnetIdA:
    Type: AWS::SSM::Parameter
    Properties:
      Name: discourse-common-SubnetIdA
      Type: String
      Description: Subnet-A to use for application
      Value: !Ref pDiscourseCommonSubnetIdA

  DiscourseCommonSubnetIdB:
    Type: AWS::SSM::Parameter
    Properties:
      Name: discourse-common-SubnetIdB
      Type: String
      Description: Subnet-B to use for application
      Value: !Ref pDiscourseCommonSubnetIdB

  DiscourseCommonVPCcidr:
    Type: AWS::SSM::Parameter
    Properties:
      Name: discourse-common-VPCcidr
      Type: String
      Description: VPC CIDR
      Value: !Ref pDiscourseCommonVPCcidr

  DiscourseCommonVpcId:
    Type: AWS::SSM::Parameter
    Properties:
      Name: discourse-common-VpcId
      Type: String
      Description: VPC id to use for application
      Value: !Ref pDiscourseCommonVpcId


#rds
  DiscourseRdsDBInstanceType:
    Type: AWS::SSM::Parameter
    Properties:
      Name: discourse-rds-DBInstanceType
      Type: String
      Description: RDS instance type for postgres
      Value: !Ref pDiscourseRdsDBInstanceType

  DiscourseRdsDBPassword:
    Type: AWS::SSM::Parameter
    Properties:
      Name: discourse-rds-DBPassword
      Type: String
      Description: Default password for postgres. Ignored if db is restored from snapshot
      Value: !Ref pDiscourseRdsDBPassword

  DiscourseRdsPostgresEngineVersion:
    Type: AWS::SSM::Parameter
    Properties:
      Name: discourse-rds-PostgresEngineVersion
      Type: String
      Description: Postgres version of database
      Value: !Ref pDiscourseRdsPostgresEngineVersion

  DiscourseRdsRDSSnapshotName:
    Type: AWS::SSM::Parameter
    Properties:
      Name: discourse-rds-RDSSnapshotName
      Type: String
      Description: Name of the snapshot from which recover db. Leave it empty if new database
      Value: !Ref pDiscourseRdsRDSSnapshotName


#application
  DiscourseAppAMIid:
    Type: AWS::SSM::Parameter
    Properties:
      Name: discourse-app-AMIid
      Type: String
      Description: Golden AMI id. It is always override by pipeline
      Value: !Ref pDiscourseAppAMIid

  DiscourseAppCertificateARN:
    Type: AWS::SSM::Parameter
    Properties:
      Name: discourse-app-CertificateARN
      Type: String
      Description: ARN of load balancer certificate
      Value: !Ref pDiscourseAppCertificateARN

  DiscourseAppInstanceName:
    Type: AWS::SSM::Parameter
    Properties:
      Name: discourse-app-InstanceName
      Type: String
      Description: Name of the EC2 instance
      Value: !Ref pDiscourseAppInstanceName

  DiscourseAppInstanceType:
    Type: AWS::SSM::Parameter
    Properties:
      Name: discourse-app-InstanceType
      Type: String
      Description: EC2 type
      Value: !Ref pDiscourseAppInstanceType

  DiscourseAppKeyName:
    Type: AWS::SSM::Parameter
    Properties:
      Name: discourse-app-KeyName
      Type: String
      Description: Keyname for EC2
      Value: !Ref pDiscourseAppKeyName

  DiscourseAppSshCidrAllow:
    Type: AWS::SSM::Parameter
    Properties:
      Name: discourse-app-SshCidrAllow
      Type: String
      Description: CIDR of allowed IPs for ssh connection to instance
      Value: !Ref pDiscourseAppSshCidrAllow


#pipeline
  DiscoursePipelineBucketName:
    Type: AWS::SSM::Parameter
    Properties:
      Name: discourse-pipeline-BucketName
      Type: String
      Description: Name of S3 bucket where pipeline store artifacts
      Value: !Ref pDiscoursePipelineBucketName

  DiscoursePipelineCodeBuildComputeType:
    Type: AWS::SSM::Parameter
    Properties:
      Name: discourse-pipeline-CodeBuildComputeType
      Type: String
      Description: Codebuild size type
      Value: !Ref pDiscoursePipelineCodeBuildComputeType

  DiscoursePipelineCodeBuildEnvironment:
    Type: AWS::SSM::Parameter
    Properties:
      Name: discourse-pipeline-CodeBuildEnvironment
      Type: String
      Description: Codebuild container name
      Value: !Ref pDiscoursePipelineCodeBuildEnvironment

  DiscoursePipelineGitHubRepoName:
    Type: AWS::SSM::Parameter
    Properties:
      Name: discourse-pipeline-GitHubRepoName
      Type: String
      Description: Name of github repo from which get the code
      Value: !Ref pDiscoursePipelineGitHubRepoName

  DiscoursePipelineGitHubToken:
    Type: AWS::SSM::Parameter
    Properties:
      Name: discourse-pipeline-GitHubToken
      Type: String
      Description: Token for reading github repository
      Value: !Ref pDiscoursePipelineGitHubToken

  DiscoursePipelineGitHubUsername:
    Type: AWS::SSM::Parameter
    Properties:
      Name: discourse-pipeline-GitHubUsername
      Type: String
      Description: Username or organization name of repository owner
      Value: !Ref pDiscoursePipelineGitHubUsername

  DiscoursePipelineNotificationMail:
    Type: AWS::SSM::Parameter
    Properties:
      Name: discourse-pipeline-NotificationMail
      Type: String
      Description: Mail to send pipeline notification
      Value: !Ref pDiscoursePipelineNotificationMail