---
- command: docker ps -qa
  register: docker_ps_qa
  sudo: yes
- command: ./launcher stop app
  when: docker_ps_qa.stdout_lines != []
  args:
    chdir: /var/discourse
  sudo: yes
- command: ./launcher start app
  args:
    chdir: /var/discourse
  sudo: yes
