---
- name: add discourse user
  user: name=discourse groups=sudo,admin
- synchronize: src=../discourse dest=/var/
  sudo: yes
- service: name=docker state=restarted
  sudo: yes
- shell: docker ps
  sudo: yes
  register: discourse_running
- command: ./launcher bootstrap app
  args:
    chdir: /var/discourse
  when: discourse_running.stdout.find('local_discourse/app') == -1
  sudo: yes
