---
- name: ensure docker is running
  service: name=docker state=restarted
  sudo: yes

- name: add discourse user
  user: name=discourse groups=sudo,admin

- git:
    repo: https://github.com/discourse/discourse_docker.git
    dest: '{{ discourse_location }}'
    update: no

- name: copy discourse configuration app.yml
  copy: src=app.yml dest={{ discourse_location }}/containers/app.yml owner=discourse group=sudo

- name: fix discourse permissions
  file: path={{ discourse_location }} owner=discourse group=discourse recurse=yes
  register: discourse_copied

- name: check if discourse is running
  command: docker ps --filter name=app --filter status=running
  register: discourse_is_running

- name: stop already running instance of discourse and rebuild it
  command: echo rebuilding discourse
  when: discourse_is_running|succeeded
  notify:
    - stop discourse
    - rebuild discourse

- name: build and run discourse
  command: echo rebuilding discourse
  when: discourse_is_running|failed
  notify:
    - rebuild discourse
