---
- name: stop discourse
  command: "{{ item }}"
  with_items:
    - ./launcher stop web_only
    - ./launcher stop data
  args:
    chdir: /var/discourse
  ignore_errors: yes
  register: stopped_discourse
  sudo: yes

- name: start discourse
  command: "{{ item }}"
  with_items:
    - ./launcher start data
    - ./launcher start web_only
  args:
    chdir: /var/discourse
  ignore_errors: yes
  sudo: yes

- name: restart discourse
  command: "{{ item }}"
  with_items:
    - ./launcher restart web_only
  args:
    chdir: /var/discourse
  ignore_errors: yes
  sudo: yes

- name: rebuild discourse
  command: "{{ item }}"
  with_items:
    - ./launcher rebuild web_only
    - ./launcher rebuild data
  args:
    chdir: /var/discourse
  ignore_errors: yes
  sudo: yes

- name: bootstrap discourse
  command: "{{ item }}"
  with_items:
    - ./launcher bootstrap data
    - ./launcher bootstrap web_only
  args:
    chdir: /var/discourse
  sudo: yes

- name: restart ssh
  sudo: yes
  action: service name=ssh state=restarted enabled=yes

- name: reload systemd
  sudo: yes
  command: systemctl daemon-reload
