---
- name: stop discourse
  command: "./launcher stop data && ./launcher stop web_only"
  args:
    chdir: /var/discourse
  ignore_errors: yes
  register: stopped_discourse
  sudo: yes

- name: start discourse
  command: "./launcher start data && ./launcher start web_only"
  args:
    chdir: /var/discourse
  ignore_errors: yes
  sudo: yes

- name: restart discourse
  command: "./launcher restart data && ./launcher restart web_only"
  args:
    chdir: /var/discourse
  ignore_errors: yes
  sudo: yes

- name: rebuild discourse
  command: "./launcher rebuild data && ./launcher rebuild web_only"
  args:
    chdir: /var/discourse
  ignore_errors: yes
  sudo: yes

- name: bootstrap discourse
  command: "./launcher bootstrap data && ./launcher bootstrap web_only"
  args:
    chdir: /var/discourse
  sudo: yes

- name: restart ssh
  sudo: yes
  action: service name=ssh state=restarted enabled=yes

- name: reload systemd
  sudo: yes
  command: systemctl daemon-reload
