---
- name: install apt packages
  apt: pkg={{ item }} state=latest
  sudo: yes
  with_items:
    - fail2ban
    - ufw
    - git
    - htop

- name: ensure fail2ban is running
  sudo: yes
  action: service name=fail2ban state=restarted enabled=yes

- name: forbid SSH root login
  sudo: yes
  lineinfile: destfile=/etc/ssh/sshd_config regexp="^PermitRootLogin" line="PermitRootLogin no" state=present
  notify:
    - restart ssh

- name: reset firewall
  sudo: yes
  action: shell ufw --force reset

- name: allow firewall authorized ports
  sudo: yes
  action: shell ufw allow {{ item }}
  with_items:
    - 22
    - 80
    - 443

- name: enable firewall
  sudo: yes
  action: shell ufw --force enable

- name: show firewall status
  sudo: yes
  action: shell ufw status

- name: copy backup cron script
  sudo: yes
  ignore_errors: true
  copy: src=backup.cron.sh dest=/home/discourse/backup.cron.sh owner=discourse group=sudo

# runs cron script @ 11,16,22:00 => 9,14,20:00 GMT+1
- cron: name="run backup cron script" minute="0" hour="11,16,22" job="sh /home/discourse/backup.cron.sh"
